# - coding: utf-8 --
version: '3.3'

services:

  geoservice:
    image: geoservice:latest
    build: .
    container_name: geoservice
    restart: on-failure
    environment:
      - FLASK_ENV=app
    ports:
      - 5000:5000
    volumes:
      - ./geoservice



